version: "3.7"
services:
  ioc:
    image: ${TCU6_IMAGE}:${TCU6_TAG}
    network_mode: host
    environment:
      - P=RF-TCU-Tests
      - EPICS_CAS_SERVER_PORT=5884
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
