version: "3.7"
services:
  ioc:
    build: "."
    image: "dockerregistry.lnls-sirius.com.br/gco/rf-tcu6:v1.5"
    network_mode: host
    environment:
      - P=RF-TCU-Tests
      - EPICS_CAS_SERVER_PORT=5884
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
